# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Firedrake Notes
author: YANG Zongze
# logo: logo.png


# https://jupyterbook.org/en/stable/structure/configure.html?highlight=only_build_toc_files#exclude-pages-from-your-build
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off' # force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  use_jupyterbook_latex: true
  latex_documents:
    targetname: firedrake_notes.tex
    title: '{\kaishu Firedrake Notes}'
    author: '\hfill YANG Zongze \\ {\small yangzongze@gmail.com}'

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - reference/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/lrtfm/notes-for-firedrake  # Online location of your book
  # path_to_book: notes # Optional path to your book, relative to the repository root
  branch: notes # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                   : ""    # A path to a favicon image
  use_edit_page_button      : false # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  use_multitoc_numbering    : false # Continuous numbering across parts/chapters
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Ba
  baseurl                   : https://zzyang.net/firedrake-notes
  google_analytics_id       : G-CMTGSGQVCB
  analytics:
  extra_footer: |
    <div>
    <!-- By <a href="https://zzyang.net/">YANG Zongze</a>  -->
    &copy; Copyright 2023.
    </div>

  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.

sphinx:
  config:
    html_show_copyright: false
    language: en
    # https://www.sphinx-doc.org/en/master/latex.html
    # latex_show_urls: footnote  # inline
    latex_elements:
      # extraclassoptions: openany
      papersize: a4paper
      cmappkg: ""
      fontenc: ""
      fontpkg: |
        % \setmonofont{DejaVu Sans Mono}
      preamble: |
        % \usepackage[linespread=1.2,punct=plain,heading=true,fontset=windows]{ctex}
        \usepackage[linespread=1.2,punct=plain,fontset=windows]{ctex}
        \usepackage[perpage]{footmisc}
      # fncychap: ""
      tableofcontents: |
        \ctexset{
          part/pagestyle = empty,
          % contentsname=目\quad 录
        }
        \addtocontents{toc}{\protect{\pdfbookmark[0]{\contentsname}{toc}}}
        \sphinxtableofcontents
        % \tableofcontents
      passoptionstopackages: |
        \PassOptionsToPackage{AutoFakeBold}{xeCJK}
      # extrapackages: 

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    # - attrs_inline
    # - attrs_block
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist