# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Firedrake Notes
author: YANG Zongze
# logo: logo.png


# https://jupyterbook.org/en/stable/structure/configure.html?highlight=only_build_toc_files#exclude-pages-from-your-build
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'cache' # force, cache

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  use_jupyterbook_latex: true
  latex_documents:
    targetname: firedrake-notes.tex
    title: '{\kaishu Firedrake Notes}'
    author: '\hfill YANG Zongze \\ {\small yangzongze@gmail.com}'

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - reference/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/lrtfm/notes-for-firedrake  # Online location of your book
  # path_to_book: notes # Optional path to your book, relative to the repository root
  branch: notes # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                   : ""    # A path to a favicon image
  use_edit_page_button      : false # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  use_multitoc_numbering    : false # Continuous numbering across parts/chapters
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Ba
  baseurl                   : https://zzyang.net/firedrake-notes
  analytics:
    google_analytics_id       : G-CMTGSGQVCB
  extra_footer: |
    <div>
    <!-- By <a href="https://zzyang.net/">YANG Zongze</a>  -->
    &copy; Copyright 2024.
    </div>

  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.

sphinx:
  extra_extensions:
    # - sphinxcontrib.mermaid
    # - sphinxcontrib.wavedrom
    - sphinxcontrib.plantuml
    - sphinxcontrib.tikz
    # - sphinxcontrib.blockdiag
  config:
    html_show_copyright: false
    language: en
    # https://www.sphinx-doc.org/en/master/latex.html
    # latex_show_urls: footnote  # inline
    latex_elements:
      extraclassoptions: twoside,openany
      papersize: a4paper
      cmappkg: ""
      # fontenc: ""
      fontpkg: |
        % \setmainfont{DejaVu Serif}
        % \setsansfont{DejaVu Sans}
        % \setmonofont{DejaVu Sans Mono}
      utf8extra: ""
      preamble: |
        \usepackage[
          linespread=1.2,
          punct=plain,
          heading=false,
          % fontset=windows,
          % scheme=chinese,
        ]{ctex}
        \usepackage[perpage]{footmisc}
        \makeatletter
        \fancypagestyle{normal}{
          \fancyhf{}
          % \fancyfoot[LE,RO]{{\py@HeaderFamily\thepage}}
          % \fancyfoot[LO]{{\py@HeaderFamily\nouppercase{\rightmark}}}
          % \fancyfoot[RE]{{\py@HeaderFamily\nouppercase{\leftmark}}}
          % \fancyhead[LE,RO]{{\py@HeaderFamily \@title, \py@release}}
          \fancyhead[RE]{{\py@HeaderFamily\nouppercase{\rightmark}}}
          \fancyhead[LO]{{\py@HeaderFamily\nouppercase{\leftmark}}}
          \fancyhead[LE,RO]{{\py@HeaderFamily\thepage}}
          \renewcommand{\headrulewidth}{0.4pt}
          \renewcommand{\footrulewidth}{0pt}
          }
        \fancypagestyle{plain}{
          \fancyhf{}
          % \fancyfoot[RO]{{\py@HeaderFamily\thepage}}
          % \if@twoside\fancyfoot[LE]{{\py@HeaderFamily\thepage}}\fi
          \fancyhead[LE,RO]{{\py@HeaderFamily\thepage}}
          \renewcommand{\headrulewidth}{0pt}
          \renewcommand{\footrulewidth}{0pt}
        }
        \makeatother
        % \titleformat{\part}%
        % [display]%  shape
        % {\large\bfseries\filcenter}%  format
        % {\huge\partname{} \thepart}%  label
        % {0pt}%  sep
        % {\thispagestyle{empty}\vspace{1.5pc}\huge}%  before-code
        % []%  after-code
        % % end \titleformat{\part}
        \ctexset{
          % part/pagestyle = empty,
          contentsname=目\quad 录
        }
        \usepackage{bookmark}
        \renewenvironment{sphinxthebibliography}[1]{%
          \cleardoublepage%
          \part*{}\bookmarksetup{startatroot}%
          \phantomsection%
          \begin{thebibliography}{#1}%
          \addcontentsline{toc}{chapter}{\bibname}%
        }{%
          \end{thebibliography}%
        }
      # fncychap: ""
      tableofcontents: |
        \phantomsection
        \addcontentsline{toc}{chapter}{\contentsname}
        \sphinxtableofcontents
      passoptionstopackages: |
        \PassOptionsToPackage{AutoFakeBold}{xeCJK}
      # extrapackages: 
      fvset: |
        \fvset{
          % fontsize=\small,
          baselinestretch=1,
        } % showspaces=true do not work

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    # - attrs_inline  # this is not supported by myst-parser 0.18.1
    # - attrs_block
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist