# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Notes on Firedrake
author: YANG Zongze
# logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off' # force

# Define the name of the latex output file for PDF builds
latex:
  use_jupyterbook_latex: true
  latex_documents:
    targetname: firedrake_notes.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/lrtfm/notes-for-firedrake  # Online location of your book
  path_to_book: notes # Optional path to your book, relative to the repository root
  branch: notes # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false

sphinx:
  config:
    language: en
    # https://www.sphinx-doc.org/en/master/latex.html
    latex_elements:
      fontpkg: '\usepackage[linespread=1,punct=plain]{ctex}'
      # extrapackages: r'\usepackage{ctex}'

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    # - attrs_inline
    # - attrs_block
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist